name: Deploy to NCP Object Storage

on:
  push:
    branches:
      - develop # 배포할 브랜치

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Install dependencies
        run: npm install

      - name: Build project
        run: npm run build # 리액트일 경우

      - name: Upload to NCP Object Storage
        uses: jakejarvis/s3-sync-action@master
        with:
          args: --acl public-read --delete
        env:
          AWS_S3_BUCKET: ${{ secrets.NCP_BUCKET_NAME }}
          AWS_ACCESS_KEY_ID: ${{ secrets.NCP_ACCESS_KEY }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.NCP_SECRET_KEY }}
          AWS_REGION: ${{ secrets.NCP_REGION }}
          SOURCE_DIR: 'build' # React 기준
          AWS_S3_ENDPOINT: ${{ secrets.NCP_ENDPOINT }}
